BackendBundle\Entity\Auto:
    type: entity
    table: auto
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        marca:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        modelo:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        anio:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
        descripcion:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        status:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        precio:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        fechaRegistro:
            type: datetime
            nullable: false
            column: fecha_registro
    lifecycleCallbacks: {  }
