BackendBundle\Entity\Cliente:
    type: entity
    table: cliente
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombres:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        apellidos:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        tel1:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
        tel2:
            type: string
            nullable: true
            length: 12
            options:
                fixed: false
        correo:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        direccion:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        status:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
                default: activo
    lifecycleCallbacks: {  }
