BackendBundle\Entity\Empleado:
    type: entity
    table: empleado
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombres:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        apellidos:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        correo:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        tel:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        fechaInicio:
            type: date
            nullable: false
            column: fecha_inicio
        fechaFin:
            type: date
            nullable: true
            column: fecha_fin
        status:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
