BackendBundle\Entity\Usuario:
    type: entity
    table: usuario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombres:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        apellidos:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        correo:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        contrasena:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        creado:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
